[tools]
node = "lts"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@herb-tools/formatter" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
"npm:pyright" = "latest"
"npm:intelephense" = "latest"

python = "latest"
uv = "latest"
ruby = "latest"
go = "latest"
terraform = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "ruby", "go", "terraform"]
