# Layout
cask "qwerty-fr"

# Install ghostty 
cask "ghostty"

# Install neovim
brew "neovim", args: ["head"] 

# Fonts
cask "font-jetbrains-mono-nerd-font"

# Cli tools
brew "stow"
brew "wget"
brew "coreutils"
brew "atuin"
brew "ripgrep"
brew "lazygit"
brew "fd"
brew "git-delta"
brew "fzf"
brew "tmux"
brew "bat"
brew "fpp"
brew "jq"
brew "zoxide"
brew "tlrc"
brew "fx"
brew "yazi"
brew "k9s"
brew "lazydocker"
brew "eza"
brew "watch"
brew "watchexec"
brew "lnav"
brew "commitizen"
brew "ripgrep-all"
brew "httpie"
brew "glow"
brew "tokei"
brew "bottom"
brew "tmux-xpanes"
brew "gh"
brew "kubectx"
brew "yt-dlp"
brew "typst"
brew "git-secret"
tap "tw93/tap"
brew "tw93/tap/mole"
brew "git-lfs"
brew "television"

# Apps
cask "docker-desktop"
cask "google-chrome"
cask "zen"
cask "postman"
tap "FelixKratz/formulae"
brew "FelixKratz/formulae/borders"
cask "nikitabobko/tap/aerospace"
cask "karabiner-elements"
cask "raycast"
cask "bettertouchtool"
cask "alt-tab"
cask "hammerspoon"
cask "displaylink"
brew "gifski"
cask "aldente"
cask "cleanshot"
cask "obsidian"

# Languages
brew "mise"
tap "shivammathur/php"
brew "shivammathur/php/php"

# Other
brew "luarocks"
brew "gnupg"
brew "poppler"
brew "pandoc"
brew "ffmpeg"
brew "imagemagick"
brew "p7zip"
brew "graphviz"
brew "pam-reattach"
brew "pkgconf"
brew "ast-grep"
