add_newline = false

[line_break]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true

[php]
disabled = true

[aws]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[python]
disabled = true

[docker_context]
disabled = true
