gui:
  scrollHeight: 10
  shortTimeFormat: 15:04
  nerdFontsVersion: "3"

quitOnTopLevelReturn: true

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme base16-256 -s
