gui:
  scrollHeight: 10
  shortTimeFormat: 15:04
  nerdFontsVersion: "3"

quitOnTopLevelReturn: true

os:
  editPreset: "nvim-remote"
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{filename}})'
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" &&  nvim --server "$NVIM" --remote {{filename}} && nvim --server "$NVIM" --remote-send ":{{line}}<CR>")'
  editAtLineAndWait: '[ -z "$NVIM" ] && (nvim -- {{dir}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{dir}})'

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme base16-256 -s
